### ISSUE TITLE
When I update frame on animation - server crashes

### ISSUE THREAD

**Issue by tmoflash** [TheCahyag/MinecraftAnimation#8]
I was using animate yesterday to test. It seemed to work fine. However, today when I was creating an animation and I updated the animation frame0 the server crashed this happened 2xs in a row. 

Here is the crash log

https://pastebin.com/WStcc08h

**Comment by TheCahyag** [comment]
Hmm.. It's weird that the nothing from the plugin comes up in the stack trace. Could you send me your database file? `/config/animation/ANIMATIONS.mv.db` Send me any trace files in that directory if any are present. I'm going to try and reproduce the issue and go from there

**Comment by TheCahyag** [comment]
Furthermore, were there any errors printed in the servers console?

**Comment by tmoflash** [comment]
I did notice something. When creating the animation. I click frame update and nothing happened. I then clicked it a 2nd time which I think caused the crash. I cannot confirm. I did not see any errors in console. But I will paste it: 
[animate_consol_log.zip](https://github.com/TheCahyag/MinecraftAnimation/files/2386642/animate_consol_log.zip)

**Comment by tmoflash** [comment]
I am new to animate, so I am not sure if this makes a difference. I was trying to make an animation on the ground diagonally. I was using a rectangle/square as a guide, I wasn't sure if this was a limitation.

**Comment by TheCahyag** [comment]
The animation you are describing is supported. There isn't a limitation on the size or orientation of the animation. Let me do some digging on this and see what I can do to help out. Could you try and recreate this problem with only Sponge and the Animation plugin? That way we know if there is a conflicting plugin or not.

**Comment by tmoflash** [comment]
I took everything out except luckperms and nucleus, could not get the issue to reproduce. I am going to add back in what I had before see if I can reproduce to confirm it is another plugin.

**Comment by TheCahyag** [comment]
Ok. Let me know when you find out what plugin. There still may be some changes I can make to interact with other plugins more harmoniously

**Comment by tmoflash** [comment]
Has not crashed but got this in console, clicked update frame a few times: [09:39:52 ERROR] [Sponge]: The Scheduler tried to run the task animation-A-100 owned by Plugin{id=animation, name=Animations, version=0.3.0, description=Animations - Allowing the creation of frame based animations., url=https://github.com/TheCahyag/MinecraftAnimation, authors=[TheCahyag], source=mods/Animation-1.12.2-0.3.0.jar}, but an error occured.

**Comment by tmoflash** [comment]
Crashed: > [09:41:56 INFO] [nucleus]: tmoflash ran the command: /animate test frame update frame1
> [09:42:00 INFO] [nucleus]: tmoflash ran the command: /animate test frame update frame1
> [09:42:30 INFO] [nucleus]: tmoflash ran the command: /animate test frame frame2 info
> [09:42:30 INFO] [animation]: Get frame (frame2): 2
> [09:42:33 INFO] [nucleus]: tmoflash ran the command: /animate test frame update frame2
> [09:42:35 INFO] [nucleus]: tmoflash ran the command: /animate test frame update frame2
> [09:43:16 INFO] [nucleus]: tmoflash ran the command: /animate test frame frame3 info
> [09:43:16 INFO] [animation]: Get frame (frame3): 1
> [09:43:18 INFO] [nucleus]: tmoflash ran the command: /animate test frame update frame3
> [09:43:20 INFO] [nucleus]: tmoflash ran the command: /animate test frame update frame3
> [09:43:20 ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1621) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) ~[nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(SourceFile:464) ~[MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[minecraft_server.1.12.2.jar:?]
at org.spongepowered.common.block.SpongeBlockSnapshot.<init>(SpongeBlockSnapshot.java:109) ~[SpongeBlockSnapshot.class:1.12.2-7.1.0-BETA-116]
at net.minecraft.world.WorldServer.createSpongeBlockSnapshot(SourceFile:3023) ~[oo.class:?]
at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:287) ~[TrackingUtil.class:1.12.2-7.1.0-BETA-116]
at net.minecraft.world.WorldServer.func_147456_g(SourceFile:1980) ~[oo.class:?]
at net.minecraft.world.WorldServer.func_72835_b(SourceFile:223) ~[oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1617) ~[MinecraftServer.class:?]
... 4 more
> [09:43:20 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2018-09-16_09.43.20-server.txt
> [09:43:20 INFO]: Stopping server

**Comment by TheCahyag** [comment]
This may be a problem with how the animation is being manipulated. In its current state (which needs to be updated evidently) after you set the animations corners (with `/animate <name> set pos1`) you can create frames, but if you change the corners again and create more frames, the old frames dont get updated. Meaning that you need to set the corners of the animation and never change them. This might solve your problem with the game crashing. I'm going to test this theory out and see if I can get the same error and if I can, I will make some modifications to handle this state change better.

**Comment by TheCahyag** [comment]
The error previously described is moved to issue #9 and this will remain as I don't know if that is the leading issue here.

**Comment by tmoflash** [comment]
Any updates on this issue?

**Comment by TheCahyag** [comment]
My apologies for taking so long on this, work has been busy. I should have time today and tomorrow to crank out a solution to this. I'm setting a soft deadline of this Friday (11/2) to have a patch for this. Thanks for the reminder @tmoflash

**Comment by TheCahyag** [comment]
@tmoflash Hope you've been having a good week, I have a solution that should avoid the problem you are having (note it does not directly fix it as I don't think I could reproduce the exact problem you were having).  I'm giving you this as an early release jar, keep in mind I still want to do some testing on it later today and get it merged into the main branch, but I'll give it to you here to try if you want. 

The change I made was to not allow users to set the animation's corners if you have 
**a)** already set the corners _and_
**b)** have frames with content

Not a great solution, but blah, I'll probably end up refining this later. Please let me know if this still crashes your server.
[Animation-1.12.2-0.3.1.23-SNAPSHOT.zip](https://github.com/TheCahyag/MinecraftAnimation/files/2544335/Animation-1.12.2-0.3.1.23-SNAPSHOT.zip)
